let perguntas = [
    { 
        numero: "1", 
        pergunta: "O que é JSX?", 
        resposta: "Uma extensão de linguagem do JavaScript", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:""},
    { 
        numero: "2", 
        pergunta: "O React é __ ", 
        resposta: "uma biblioteca JavaScript para construção de interfaces", 
        status: "fechada" ,
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:""},
    { 
        numero: "3", 
        pergunta: "Componentes devem iniciar com __ ", 
        resposta: "letra maiúscula", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" },
    { 
        numero: "4", 
        pergunta: "Podemos colocar __ dentro do JSX", 
        resposta: "expressões", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" },
    { 
        numero: "5", 
        pergunta: "O ReactDOM nos ajuda __ ", 
        resposta: "interagindo com a DOM para colocar componentes React na mesma", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" },
    { 
        numero: "6", 
        pergunta: "Usamos o npm para __ ", 
        resposta: "gerenciar os pacotes necessários e suas dependências", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" },
    { 
        numero: "7", 
        pergunta: "Usamos props para __ ", 
        resposta: "passar diferentes informações para componentes ", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" },
    { 
        numero: "8", 
        pergunta: "Usamos estado (state) para __", 
        resposta: "dizer para o React quais informações quando atualizadas devem renderizar a tela novamente", 
        status: "fechada",
        fonte: "#333333",
        tracejado: "false",
        icone:"play-outline",
        corIcone:"" }
]

export default perguntas